// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.44
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ClickupVS.Windows
{
    using System;

    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidClickupVSPackageString = "6bc9c410-c60b-436f-91a3-9dbf18659c26";
        public static Guid guidClickupVSPackage = new Guid(guidClickupVSPackageString);

        public const string guidClickupVSPackageCmdSetString = "6f2a88ec-9c7c-46df-a452-e109da18d336";
        public static Guid guidClickupVSPackageCmdSet = new Guid(guidClickupVSPackageCmdSetString);

        public const string guidImagesString = "baf2efbd-5b81-4665-ab32-8d4f0d212cac";
        public static Guid guidImages = new Guid(guidImagesString);
    }

    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int ClickupToolWindowCommandId = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}
