// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ClickUpVS
{
	internal sealed partial class Vsix
	{
		public const string Id = "ClickUpVS.3d0f9772-0109-4bc1-8992-3ec214616fc7";
		public const string Name = "ClickUpVS";
		public const string Description = @"Empty VSIX Project.";
		public const string Language = "en-US";
		public const string Version = "1.0";
		public const string Author = "Company";
		public const string Tags = "";
	}
}
